#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Create ru-RU.ini translation files for all PRISM Live Studio modules."""

import os

BASE = "/Applications/PRISMLiveStudio.app/Contents/Resources/data/prism-studio/locale"

modules = {}

modules["Chat"] = """Chat.Band.And.RTMP.Not.Supported="Функция чата не поддерживается для каналов BAND и пользовательских каналов."
Chat.Band.And.Twitter.Not.Supported="Twitter и BAND не поддерживают чат. Проверьте чат на сайте платформы."
Chat.Band.Not.Supported="Функция чата не поддерживается для каналов BAND. Пожалуйста, проверьте чат на странице BAND."
Chat.Band.Twitter.And.RTMP.Not.Supported="Twitter, BAND и пользовательские каналы не поддерживают чат."
Chat.Property.ChatSource.NoSupportChannel.InStreaming="Источник PRISM Chat недоступен для трансляций, не поддерживающих чат."
Chat.SourceButton.NoPlatform="Добавить источник PRISM Chat"
Chat.SourceButton.OnePlatform="Добавить источник чата"
Chat.Toast.ChatSource.NoSupportChannel.WhenStreaming="Источник PRISM Chat недоступен для трансляций, не поддерживающих чат."
Chat.Toast.NoChatSource.WhenStreaming="Вы можете добавить источник чата для канала %1, на котором сейчас ведёте трансляцию. Попробуйте использовать PRISM Chat из списка источников."
Chat.Toast.RTMP.Not.Supported="Комментарии для каналов с пользовательским подключением можно проверить на сайте соответствующей платформы."
Chat.Twitter.And.RTMP.Not.Supported="Twitter и пользовательские каналы не поддерживают чат."
Chat.Twitter.Not.Supported="Twitter не поддерживает чат. Проверьте чат в окне Twitter."
chat.rtmp.placehoder.nochannel="Вы можете общаться со своими фанатами во время трансляции."
chat.rtmp.placehoder.onlyrtmp="Функция чата не поддерживается для текущего канала."
chat.title="Чат"
"""

modules["ChatTemplate"] = """Bibid.Color="Яркий"
ChatTemplate.Common.Nick="Общий никнейм"
ChatTemplate.Custom.Empty.Default="Выберите шаблон темы и добавьте свою тему в подробных настройках"
ChatTemplate.Default.Font="Шрифт"
ChatTemplate.FontandColor.Settings="Настройки шрифта и фона"
ChatTemplate.Function="Настройки функций чата"
ChatTemplate.Message.Text="Сообщение чата"
ChatTemplate.Mgr.Nick="Менеджер"
ChatTemplate.Mgr.Nick.Tooltip="Поддерживается только на платформах NAVER TV, SOOP, Chzzk и NAVER Cloud B2B"
ChatTemplate.Outline="Эффект обводки"
ChatTemplate.Outline.Size="Размер"
ChatTemplate.Over.Number.Ten="Можно добавить до 10 пользовательских тем."
ChatTemplate.Rename.Content="Введите название вашей пользовательской темы"
ChatTemplate.Rename.Exist="Это название уже используется."
ChatTemplate.Rename.Title="Название пользовательской темы"
ChatTemplate.ResizeCT.Button="Изменить размер чата"
ChatTemplate.ResizeCT.ToolTip="Свободно настраивайте размер чата, перетаскивая край окна изменения размера чата."
ChatTemplate.Save.Tempate.Button="Сохранить как пользовательскую тему"
ChatTemplate.Select.BK="Фон чата"
ChatTemplate.Select.Theme="Выбор темы"
ChatTemplate.Single.Bk.Color="Фон отдельного сообщения"
ChatTemplate.Subcribe.Text="Платная подписка"
ChatTemplate.Subcribe.Text.Tooltip="Поддерживается только на платформе YouTube"
ChatTemplate.Template.Tab.Tips="* Это предварительный просмотр чата. Фактический чат будет отображаться после начала трансляции."
ChatTemplate.Total.Bk="Общий фон чата"
ChatTemplate.Window.Alpha="Прозрачность окна чата"
ChatTemplate.display.icon.display="Отображение значков"
ChatTemplate.display.idIcon="ID"
ChatTemplate.display.levelIcon="Значок ранга"
ChatTemplate.display.levelIcon.tooltip="При включении значок будет отображаться перед ID."
ChatTemplate.display.platformIcon="Логотип платформы"
ChatTemplate.display.platformType="Тип платформы"
ChatTemplate.display.platformType.tooltip="Выбранная платформа не отображается в реальном времени в области предварительного просмотра до начала трансляции. Проверьте после начала трансляции."
ChatTemplate.motion.random="Случайно"
ChatTemplate.motion.shaking="Тряска"
ChatTemplate.motion.wave="Волна"
ChatTemplate.motions="Анимация чата"
ChatTemplate.option.disapper="Эффект исчезновения чата"
ChatTemplate.option.disapper.off="Выкл"
ChatTemplate.option.disapper.on="Вкл"
ChatTemplate.option.height="Высота"
ChatTemplate.option.left.align="Выровнять чат по левому краю"
ChatTemplate.option.right.align="Выровнять чат по правому краю"
ChatTemplate.option.size="Размер чата"
ChatTemplate.option.sort="Выравнивание чата"
ChatTemplate.option.warp="Перенос строк"
ChatTemplate.option.width="Ширина"
Ct.Remove.Custom.Template="Вы хотите удалить %1?"
Pastel.Color="Пастельный"
Radom.Color="Случайный цвет"
Single.Color="Один цвет"
"""

modules["ChzzkSponsor"] = """CHZZKSponsor.Chat.Sponsorship="Спонсорство через чат"
CHZZKSponsor.Describe="Это предварительный просмотр уведомления о спонсорстве. Фактическое уведомление будет отображаться после начала трансляции.\\nКогда вы нажмёте кнопку \\"Отправить тестовое уведомление\\" на странице настроек уведомлений CHZZK Studio, \\nвы сможете просмотреть настроенное уведомление перед трансляцией."
CHZZKSponsor.GetUrlFail="Не удалось получить URL для уведомления о спонсорстве CHZZK. Проверив монетизацию в сервисе CHZZK, обновите канал и добавьте виджет уведомления о спонсорстве снова."
CHZZKSponsor.GotoStudio="Перейти в CHZZK Studio"
CHZZKSponsor.GotoVerification="Подтвердить"
CHZZKSponsor.Mission.Sponsorship="Спонсировать миссию"
CHZZKSponsor.Notification="Выберите уведомление о спонсорстве"
CHZZKSponsor.Tooltip="Невозможно настроить уведомление о спонсорстве в PRISM. \\nПожалуйста, отредактируйте в CHZZK Studio."
CHZZKSponsor.Video.Sponsorship="Видеоспонсорство"
sourceMenu.chzzksponsor.item.desc="Показывать уведомления о донатах и подписках CHZZK в реальном времени."
"""

modules["Drawpen"] = """drawpen.toolbar.arrow.toolTip="Стрелка"
drawpen.toolbar.clear.toolTip="Удалить всё"
drawpen.toolbar.color.toolTip="Выбрать цвет"
drawpen.toolbar.earse.toolTip="Ластик"
drawpen.toolbar.exit.text="Закрыть"
drawpen.toolbar.glowpen.toolTip="Светящееся перо"
drawpen.toolbar.highlighter.toolTip="Маркер"
drawpen.toolbar.line.toolTip="Линия"
drawpen.toolbar.line.width.toolTip="Выбрать толщину"
drawpen.toolbar.pen.toolTip="Перо"
drawpen.toolbar.rect.toolTip="Квадрат"
drawpen.toolbar.redo.toolTip="Повторить"
drawpen.toolbar.round.toolTip="Круг"
drawpen.toolbar.shape.seclect.toolTip="Выбрать фигуру"
drawpen.toolbar.triangle.toolTip="Треугольник"
drawpen.toolbar.undo.toolTip="Отменить"
drawpen.toolbar.visible.toolTip="Скрыть"
drawpen.view.main.button.toolTip="Режим рисования"
"""

modules["DualOutput"] = """DualOutput.3rd.Plugin.In.Using="Двойной вывод невозможен, так как %1 использует PRISM."
DualOutput.CloseStudioMode="Двойной вывод недоступен в режиме студии. Хотите отключить режим студии?"
DualOutput.NewFunction="Используйте двойной вывод для одновременной трансляции в горизонтальном и вертикальном разрешении!"
DualOutput.Preview.Title.Horizontal="Горизонтальный вывод"
DualOutput.Preview.Title.Horizontal.Tip.Hide="Скрыть горизонтальный предпросмотр"
DualOutput.Preview.Title.Horizontal.Tip.Show="Показать горизонтальный предпросмотр"
DualOutput.Preview.Title.Settings="Настройки двойного вывода"
DualOutput.Preview.Title.Vertical="Вертикальный вывод"
DualOutput.Preview.Title.Vertical.Tip.Hide="Скрыть вертикальный предпросмотр"
DualOutput.Preview.Title.Vertical.Tip.Show="Показать вертикальный предпросмотр"
DualOutput.Settings.Video.Horizontal="Горизонтальный"
DualOutput.Settings.Video.Switch="Использовать двойной вывод"
DualOutput.Settings.Video.Switch.Tooltip="Транслировать одновременно в горизонтальном и вертикальном разрешении."
DualOutput.Settings.Video.Vertical="Вертикальный"
DualOutput.Streaming.No.Both="Для использования двойного вывода настройте каналы как горизонтального, так и вертикального вывода."
DualOutput.Streaming.No.Horizontal="Настроен только вертикальный канал вывода. Для использования двойного вывода настройте оба канала. Если вы хотите транслировать только в вертикальном формате, отключите двойной вывод."
DualOutput.Streaming.No.Platform="Двойной вывод активен. Пожалуйста, настройте каналы горизонтального и вертикального вывода."
DualOutput.Streaming.No.Vertical="Настроен только горизонтальный канал вывода. Для использования двойного вывода настройте оба канала. Если вы хотите транслировать только в горизонтальном формате, отключите двойной вывод."
DualOutput.StudioModeDisabled="Режим студии недоступен при использовании двойного вывода."
DualOutput.Title="Двойной вывод"
"""

modules["facebook"] = """Facebook.Group.Disabled.Link="Изменение политики Facebook"
Facebook.Group.Disabled.Text="Групповые трансляции больше не поддерживаются из-за %1."
"""

modules["libui"] = """Alert.ErrorMessage.ContactUs="Связаться"
Alert.ErrorMessage.ErrorCode="Код ошибки : %1"
Alert.ErrorMessage.Guide="При обращении в службу поддержки приложите скриншот текущего экрана."
Alert.ErrorMessage.UserId="Уникальный номер : %1"
Copy.UserId.ToolTip="Скопировать идентификационный номер"
Dock.Advance.More="Ещё"
"""

modules["Mutex"] = """Remux.Tooltip="Для работы с Remux перетащите файл в это окно или загрузите файл для обработки в ячейке записи PRISM."
"""

modules["obs-ndi"] = """Ndi.Source.NoRuntimeFound="Среда выполнения NDI™ не найдена. Пожалуйста, установите среду выполнения и добавьте источник снова."
Ndi.Source.RuntimeInitializeFail="Не удалось инициализировать среду выполнения NDI™."
"""

modules["MobileSource"] = """PrismMobile.device_disconnected="Отключено из-за сбоя повторного подключения мобильного устройства."
PrismMobile.device_lost="Мобильное соединение нестабильно.\\nПопытка переподключения."
PrismMobile.device_try_again="Повторить"
PrismMobile.device_unlink="Отключить"
QRCode.tips="Установите и запустите PRISM (мобильное приложение) и отсканируйте QR-код через меню CONNECT для подключения."
Source.ErrorTips.PrismMobile.Error="Ошибка источника PRISM Mobile"
wifihelper.title="Подключить PRISM (мобильный) к ПК"
wifihelper.top.left.text="Подключение через Wi-Fi"
wifihelper.top.right.text="Подключение через USB"
wifihelper.usb.first.page.tip="Подключение через USB пока недоступно."
wifihelper.wifi.connection.tip="Советы по подключению Wi-Fi"
wifihelper.wifi.first.tip="Добавьте PRISM как мобильный источник на ПК."
wifihelper.wifi.home.tip="Подключитесь к Wi-Fi и\\n добавьте PRISM (мобильное приложение)\\n как источник камеры на ПК!"
wifihelper.wifi.second.tip="Проверьте QR-код\\n в окне свойств мобильного источника\\n PRISM."
wifihelper.wifi.third.tip="Установите и запустите PRISM (мобильное приложение),\\n и отсканируйте QR-код\\n через меню CONNECT для подключения."
wifihelper.wifi.tip.description="<p style=\\"line-height:20px;\\">Убедитесь, что ваш ПК и мобильное устройство подключены к одной сети Wi-Fi.</p>"
wifihelper.wifi.tip.title="Подключение к одной сети Wi-Fi"
"""

modules["Music"] = """Bgm.Add.Free.Music="Добавить бесплатную музыку PRISM"
Bgm.Add.Free.Music.From.Library="Вы можете добавить музыку, нажав кнопку \\n[Добавить музыку] ниже."
Bgm.Add.Free.Music.Once="Один и тот же источник можно добавить только один раз."
Bgm.Add.Local.File="Добавить локальный файл"
Bgm.Add.Music="Добавить музыку"
Bgm.Add.Source="Добавить источник"
Bgm.Enable.Playlist="Включите источник музыкального плейлиста для воспроизведения музыки."
Bgm.Existed.Same.Url.Tips="Одинаковый музыкальный файл нельзя добавить на ПК."
Bgm.Free.Music.Local.File="Локальный файл"
Bgm.Next="Следующий"
Bgm.No.Free.Music="Нет источника музыкального плейлиста\\n для воспроизведения в этой сцене.\\n Пожалуйста, добавьте или активируйте источник."
Bgm.No.Network.Toast="Музыку невозможно воспроизвести, так как нет сетевого подключения."
Bgm.No.Repeat="Отключить повтор"
Bgm.No.Songs.Being.Played="Нет воспроизводимой песни."
Bgm.Pause="Пауза"
Bgm.Play="Воспроизвести"
Bgm.PlayInOrder="Отключить перемешивание"
Bgm.Preview.Played="Предпросмотр может воспроизводиться во время трансляции."
Bgm.Previous="Предыдущий"
Bgm.Repeat="Повторять все"
Bgm.Repeat.One="Повторять один трек"
Bgm.Shuffle="Включить перемешивание"
Bgm.Songs.Invalid.Toast="%1 невозможно воспроизвести из-за ошибки"
Bgm.Title="Музыкальный плейлист"
Bgm.library.no.network="Предпросмотр невозможен, так как сеть не подключена."
Bgm.library.preview.off="Предпросмотр музыки выкл"
Bgm.library.preview.on="Предпросмотр музыки вкл"
Bgm.library.selected.more="%1 песен|выбрано"
Bgm.library.selected.one="1 песня|выбрана"
Bgm.library.title="Музыкальный плейлист"
"""

modules["HelpMenu"] = """Contact.Check.Network.Error="Произошла сетевая ошибка.\\nПожалуйста, попробуйте снова."
Contact.Email.Format.Error="Пожалуйста, проверьте ваш Email."
Contact.Email.Report.ID.Prefix="Идентификационный номер"
Contact.Email.Title="Контактный email"
Contact.File.Format.Error="Пожалуйста, проверьте формат файла."
Contact.File.Max.Count="Вы можете прикрепить до четырёх файлов."
Contact.Inquiry.Type="Тип обращения"
Contact.Inquiry.Type.Advice="Предложение функции"
Contact.Inquiry.Type.Consult="Вопрос по использованию"
Contact.Inquiry.Type.Error="Сообщение об ошибке"
Contact.Inquiry.Type.Other="Другое"
Contact.Inquiry.Type.Plus="Вопросы по подписке PRISM Plus"
Contact.Report.File.Max10M="Размер файла не должен превышать 10 МБ."
Contact.Report.File.Max20M="Вы можете прикрепить до 20 МБ."
Contact.Report.File.Placeholder="Пожалуйста, прикрепите файлы."
Contact.Report.File.Select="Прикрепить файл"
Contact.Report.Question="Обращение"
Contact.Report.Question.Placeholder="Пожалуйста, введите подробности. (Минимум 20 символов)"
Contact.Report.Send="Отправить"
Contact.Top.Window.Title="Связаться с нами"
Main.About.Text.Currentversion="Текущая версия"
MainFrame.SideBar.Help.ContactUs="Связаться с нами"
MainFrame.SideBar.Help.PrismFAQ="PRISM FAQ"
MainFrame.SideBar.Help.PrismWebsite="Сайт PRISM"
MainFrame.SideBar.Help.checkUpdate="Проверить обновления"
Notice.Bottom.Learn.Button.Text="Подробнее"
Update.Bottom.Force.Button.Text="Обновить сейчас"
Update.Bottom.Next.Button.Text="Обновить позже"
Update.Force.Tooltip.Virtual.Camera.Active="Невозможно обновить, пока другая программа использует виртуальную камеру PRISM."
Update.Lastest.Version.Title="Вы используете последнюю версию PRISM."
Update.Toptip.Advise.Text="Обнаружено обновление.\\n Хотите обновить?"
Update.Toptip.Force.Text="Недоступно до обновления.\\n Хотите обновить сейчас?"
"""

modules["Laboratory"] = """Basic.resource.downlaod.failed.retry="Функция недоступна, так как не удалось загрузить ресурс. Проверьте состояние сети и попробуйте снова."
laboratory.default.desc="Находите и используйте новейшие интересные и экспериментальные функции в PRISM Lab. Нажмите на каждую\\nфункцию, чтобы просмотреть подробности и начать."
laboratory.default.title="PRISM Lab"
laboratory.item.Installing="Установка"
laboratory.item.close.restart.text="Изменение настроек этой функции требует перезапуска программы.\\nХотите перезапустить сейчас?"
laboratory.item.install="Установить"
laboratory.item.install.content="Для использования этой лабораторной функции требуется установка."
laboratory.item.install.finished.restartapp.content="Установка завершена.\\nЭта функция требует перезапуска программы.\\nХотите перезапустить сейчас?"
laboratory.item.open.network.failed.text="Произошла сетевая ошибка.\\n Пожалуйста, попробуйте снова."
laboratory.item.open.other.reason.failed.text="Произошла неизвестная ошибка.\\nПожалуйста, попробуйте снова."
laboratory.item.open.restart.text="Эта функция требует перезапуска программы.\\nХотите перезапустить сейчас?"
laboratory.item.open.unused="Отключено"
laboratory.item.open.using="Включено"
laboratory.plugin.beauty.beauty_label="Моделирование"
laboratory.plugin.beauty.error.no.face="Лицо не обнаружено. Сделайте фронтальное фото лица."
laboratory.plugin.beauty.error.out.of.range="Угол наклона лица вне допустимого диапазона. Пожалуйста, сделайте фронтальное фото снова."
laboratory.plugin.beauty.error.unknown="Произошла неизвестная ошибка в НОВОМ эффекте красоты. Попробуйте снова через некоторое время."
laboratory.plugin.beauty.face.nosource="Нет источника"
laboratory.plugin.beauty.face.notice="Пожалуйста, добавьте источник\\n PRISM Camera для использования эффектов красоты."
laboratory.plugin.beauty.face.title="НОВЫЙ эффект красоты"
laboratory.plugin.beauty.model.describe="Сделайте фото вашей модели."
laboratory.plugin.beauty.notice.beautyIsOn="Выбранный источник PRISM Camera использует эффект красоты. \\nОтключите эффект красоты перед фотографированием."
laboratory.plugin.beauty.notice.close.notice="Функция НОВОГО эффекта красоты применяется к источнику PRISM Camera. \\nХотите прекратить использование функции?"
laboratory.plugin.beauty.photo.describe="Попробуйте НОВЫЙ эффект красоты, сделав селфи."
laboratory.plugin.beauty.photo.title="Сделать фото"
laboratory.plugin.beauty.recordingOrLive.question="НОВЫЙ эффект красоты может быть временно приостановлен при фотографировании. \\nХотите продолжить?"
laboratory.plugin.beauty.reset="Сбросить"
laboratory.plugin.beauty.smoothLabel="Сглаживание"
laboratory.plugin.beauty.source.title="Выбрать источник"
laboratory.plugin.beauty.takephoto="Сделать фото"
laboratory.plugin.beauty.tips="Пожалуйста, сделайте фото вашего лица."
laboratory.plugin.beauty.title="НОВЫЙ эффект красоты"
laboratory.plugin.beauty.whitenLabel="Отбеливание"
laboratory.plugin.takecamera.apply="Применить"
laboratory.plugin.takecamera.camera.beusing="Устройство используется другой программой."
laboratory.plugin.takecamera.camera.error="Используется другой программой\\nили произошла неизвестная ошибка."
laboratory.plugin.takecamera.camera.loadinglist="Устройство PRISM Camera загружается. Пожалуйста, подождите."
laboratory.plugin.takecamera.camera.nodevice="Нет устройства"
laboratory.plugin.takecamera.camera.notfound="Устройство не найдено."
laboratory.plugin.takecamera.cancel="Отмена"
laboratory.plugin.takecamera.notice="Уведомление"
laboratory.plugin.takecamera.snapshot.title="Сделать фото"
laboratory.plugin.takecamera.snapshot.wait="Пожалуйста, подождите немного."
"""

modules["RemoteControl"] = """guide.remotecontrol.new="Используйте ваш телефон как пульт управления."
remotecontrol.connect.check.wifi="Проверьте подключение устройства и Wi-Fi."
remotecontrol.connect.connect.hint="Подключено к\\n%1."
remotecontrol.connect.device="Устройство"
remotecontrol.connect.fail.connect="Не удалось подключиться к пульту управления."
remotecontrol.connect.fail.disconnect="Пульт управления был отключён."
remotecontrol.connect.fail.repeat="Пульт управления может подключаться только к одному мобильному устройству.\\nПожалуйста, отключите текущее устройство и попробуйте снова."
remotecontrol.connect.guide.text="Отсканируйте QR-код в меню CONNECT мобильного приложения PRISM,\\nили выберите этот ПК в списке \\"Доступные устройства\\"."
remotecontrol.connect.guide.title="Управляйте трансляциями PRISM удалённо с помощью мобильного устройства."
remotecontrol.connect.status.connecting="Подключение…"
remotecontrol.connect.status.disconnect="Отключить"
remotecontrol.history.button.text="Просмотр истории операций"
remotecontrol.history.guide.text="Проверьте историю операций в локальной папке."
sidebar.remotecontrol.mac.title="Подключить пульт управления (Бета)"
sidebar.remotecontrol.tooltip="Подключить пульт управления"
"""

modules["ResolutionGuide"] = """Bitrate.Guide="Руководство по настройкам передачи"
Resolution.ButtonTips="Ознакомьтесь с руководством по настройкам вывода для %1 и попробуйте установить рекомендуемое разрешение."
Resolution.CustomRTMPTips="Ознакомьтесь с руководством по настройкам вывода и попробуйте установить рекомендуемое разрешение."
Resolution.InputIsActived="В данный момент выводится видео. Пожалуйста, отключите все выводы для изменения настроек экрана."
Resolution.OtherPluginOutputActived="Настройки экрана нельзя изменить во время трансляции %1."
Resolution.VirtualCamIsActived="Настройки экрана нельзя изменить, пока другая программа использует виртуальную камеру PRISM."
Resolution.VirtualCamIsActived.SettingsDisabled.Tips="Настройки нельзя изменить, пока другая программа использует виртуальную камеру PRISM."
ResolutionGuide.Apply="Применить сейчас"
ResolutionGuide.ApplyCol="Рекомендуемое разрешение"
ResolutionGuide.ApplyNowBtn="Применить сейчас"
ResolutionGuide.B2BBitrate="Битрейт видео"
ResolutionGuide.B2BEmptyList="Руководство по настройкам вывода не установлено. Пожалуйста, свяжитесь с %1."
ResolutionGuide.B2BFPS="Разрешение/FPS"
ResolutionGuide.B2BIcon="Шаблон"
ResolutionGuide.B2BKeyFrameInterval="Интервал ключевых кадров"
ResolutionGuide.B2BNetworkError="Невозможно загрузить список.\\n Пожалуйста, проверьте состояние сети и попробуйте снова."
ResolutionGuide.DescriptionCol="Ограниченные функции"
ResolutionGuide.HorizontalApply="Применить к горизонтальному выводу"
ResolutionGuide.Icon="Платформа"
ResolutionGuide.InvalidResolution="Это разрешение не поддерживается %1. Ознакомьтесь с руководством по настройкам вывода платформы и установите рекомендуемое разрешение."
ResolutionGuide.MainTitle="Руководство по настройкам вывода"
ResolutionGuide.NCP.MainTitle="Руководство по настройкам вывода"
ResolutionGuide.NewSubTitle="Пожалуйста, воспользуйтесь руководством по настройке для установки разрешения."
ResolutionGuide.Other="Другое"
ResolutionGuide.QuestionContent="Изменить на рекомендуемое разрешение %1? (%2)"
ResolutionGuide.SubTitle="Пожалуйста, ознакомьтесь с руководством по настройкам вывода для платформы и установите разрешение соответственно.\\n(Поддерживаемые разрешения зависят от политики платформы.)"
ResolutionGuide.Tip=" : Мультистриминг недоступен для разрешений выше 1080p (для всех платформ)."
ResolutionGuide.VerticalApply="Применить к вертикальному выводу"
ResolutionGuide.commonPage="Общее"
updat.B2B.Resolution="Обновить руководство по настройкам вывода"
"""

modules["SceneCollection"] = """Basic.Main.AddSceneCollection.Text="Пожалуйста, введите название набора сцен"
Basic.Main.AddSceneCollection.Title="Создать новый набор сцен"
Basic.Main.CopySceneCollection.Title="Копировать набор сцен"
Basic.Main.RenameSceneCollection.Title="Переименовать набор сцен"
Basic.Main.SaveSceneCollection.Text="Текущая информация о сценах и источниках не будет сохранена при выходе из аккаунта. Хотите сохранить файл набора сцен?"
Basic.Scene.Display.Method="Список сцен"
OBSClassic="OBS Classic"
OBSStudio="OBS Studio"
Scene.Collection.Apply="Применить"
Scene.Collection.Confirm.Text.To.Thumbnail="Отображать список сцен в виде миниатюр. Миниатюры обновляются только при смене сцены, при этом могут кратковременно использоваться ресурсы рабочего стола. Хотите переключить?"
Scene.Collection.Confirm.Thumbnail.To.Text="Отображать список сцен только текстом. Это самый стабильный вариант с минимальным влиянием на производительность. Хотите переключить?"
Scene.Collection.Delete="Удалить"
Scene.Collection.Duplicate="Дублировать"
Scene.Collection.Export="Экспорт набора сцен"
Scene.Collection.Import.Error="Выбранный файл набора сцен повреждён или не поддерживается (PRISM поддерживает импорт psc или json). Проверьте файл и попробуйте снова."
Scene.Collection.Import.From.Local="Импорт из локальной папки"
Scene.Collection.Import.From.Local.Win="Локальный"
Scene.Collection.Import.From.Other="Импорт из другой программы"
Scene.Collection.Import.From.Other.Win="OBS и другие программы"
Scene.Collection.Import.NotFound="Выбранный файл набора сцен не существует. Проверьте и попробуйте снова"
Scene.Collection.Importer.Help.Tooltip="Импорт файлов наборов сцен из OBS\\nили других программ."
Scene.Collection.Importer.Name="Название"
Scene.Collection.Importer.No.Scenes="Нет наборов сцен для импорта из других программ."
Scene.Collection.Importer.Program="Обнаруженная программа"
Scene.Collection.Importer.Scenes.Selected="<font color=\\"#effc35\\">Выбрано %1 наборов сцен</font>."
Scene.Collection.Rename="Переименовать"
Scene.Collection.Save.Day="Сохранено %1 дней назад"
Scene.Collection.Save.Hour="Сохранено %1 часов назад"
Scene.Collection.Save.Minute="Сохранено %1 минут назад"
Scene.Collection.Select.Guide="Попробуйте различные шаблоны сцен для вашей трансляции."
Scene.Collection.Select.Template="Выбрать шаблон сцены"
Scene.Collection.View.Add="Новый"
Scene.Collection.View.Help.Tooltip="Дважды щёлкните по набору сцен для применения к главному окну.\\nЭкспортируйте наборы сцен в формате psc или json.\\n- psc: Нажмите для запуска PRISM\\n- json: Откройте набор сцен в других программах"
Scene.Collection.View.Import="Импорт"
Scene.Collection.View.Management="Управление наборами сцен"
Scene.Collection.View.No.Data="Результаты поиска не найдены."
Setting.Scene.Display.Method="Метод отображения"
Setting.Scene.Display.Text.Tips="Отображать список сцен только текстом. Это самый стабильный вариант с минимальным влиянием на производительность."
Setting.Scene.Display.Text.View="Текст"
Setting.Scene.Display.Thumbnail.Tips="Сцены отображаются как миниатюры для быстрого просмотра. Миниатюры обновляются только при смене сцены. В процессе обновления ресурсы рабочего стола могут кратковременно использоваться."
Setting.Scene.Display.Thumbnail.View="Миниатюры — Авто-обновление при изменении"
Streamlabs="Streamlabs"
XSplitBroadcaster="XSplit Broadcaster"
"""

modules["SceneTemplate"] = """SceneTemplate.Alert.Download.Failed="Не удалось загрузить некоторые ресурсы шаблона сцены. Для перезагрузки нажмите кнопку Обновить или откройте окно шаблонов сцен заново."
SceneTemplate.All="Все"
SceneTemplate.Button.Retry="Повторить"
SceneTemplate.Change.resolution="Применить сейчас"
SceneTemplate.Description="Попробуйте различные шаблоны сцен для стриминга одним нажатием. Установленные шаблоны автоматически добавляются в список наборов сцен."
SceneTemplate.Detail.Scene.Resolution="Разрешение изображения %1"
SceneTemplate.Detail.Scene.Resolution.Tip="Если вы хотите использовать изображения 1080x1920, заранее установите разрешение 1080x1920 и установите шаблон."
SceneTemplate.Free="Бесплатно"
SceneTemplate.Get.Scene.List.Fail.Tip="Не удалось получить список сцен. Хотите запросить повторно?"
SceneTemplate.Horizontal.Template="Это горизонтальный шаблон. Попробуйте изменить рекомендуемые настройки разрешения. (Соотношение 16:9)"
SceneTemplate.Install.Button="Установить шаблон"
SceneTemplate.Install.Common.Error="Шаблон не был установлен. Пожалуйста, попробуйте снова."
SceneTemplate.Install.Source.Has.Update.Tip="Источник этого шаблона сцены обновлён. Переустановите шаблон сцены из окна шаблонов или добавьте источник заново."
SceneTemplate.Install.Source.Not.Found.Error="Этот шаблон сцены поддерживается только в версиях %1 и выше. Обновите приложение и попробуйте снова."
SceneTemplate.Installing.Button="Установка"
SceneTemplate.ItemForPlus="Это премиум-шаблон сцены.\\nИспользуйте различные шаблоны сцен с подпиской Plus."
SceneTemplate.Keep.resolution="Не менять"
SceneTemplate.Label.Loading="Загрузка ресурса. Пожалуйста, подождите."
SceneTemplate.Label.Retry="Не удалось загрузить список.\\nПожалуйста, попробуйте снова."
SceneTemplate.Label.Showing="Загрузка ресурсов. Пожалуйста, подождите немного."
SceneTemplate.Plus="Plus"
SceneTemplate.Recommend="По рекомендации"
SceneTemplate.Scene.Count="%1 сцен"
SceneTemplate.Scene.Count.Tips="Количество сцен"
SceneTemplate.Scene.Return.Button="Вернуться к списку"
SceneTemplate.Title="Шаблон сцены"
SceneTemplate.Vertical.Template="Это вертикальный шаблон. Попробуйте изменить рекомендуемые настройки разрешения. (Соотношение 9:16)"
SceneTemplate.View.Detail.Button="Подробнее"
latest="Сортировка по новизне"
popular="По популярности"
"""

modules["Settings"] = """Basic.MainMenu.File.Logout="Выйти"
Basic.Settings.Accessibility.ColorOverrides.SelectPurple="Направляющая выравнивания источников"
Basic.Settings.General.EnablePreviewZoom="Масштабирование экрана предпросмотра"
Basic.Settings.General.TogglePreviewProgramLabels="Показывать подписи сцен"
Basic.Settings.General.language.changed="Изменение языка требует перезапуска программы. Хотите применить изменение сейчас?"
Basic.Settings.Subscriber="Подписка"
Basic.Settings.Subscriber.B2B.Status="Корпоративный аккаунт"
Basic.Settings.Subscriber.B2B.Tip="Корпоративные аккаунты имеют полный доступ ко всем преимуществам Plus."
Basic.Settings.Subscriber.Detail="Детали подписки"
Basic.Settings.Subscriber.Mobile.Tip="Управление подпиской доступно в мобильном приложении PRISM Live."
Basic.Settings.Subscriber.Plus="PRISM Plus"
Basic.Settings.Subscriber.Plus.Status="Подписан"
Basic.Settings.Subscriber.Renewal.Auto="- Продление"
Basic.Settings.Subscriber.Renewal.Expired="- Истекает"
Basic.Settings.Subscriber.Rights.Button="Обзор преимуществ подписки"
Basic.Settings.Subscriber.Try.Status="Бесплатная пробная версия"
Basic.Settings.Subscriber.Try.Tip="Попробуйте все премиум-функции PRISM для ПК, мобильных устройств и Lens бесплатно в течение 2 недель!"
DualOutput.Settings.AudioTrack.Tip="Вы можете выбрать нужную аудиодорожку для каждого горизонтального/вертикального вывода при использовании двойного вывода."
MultitrackVideo.IncompatibleSettings.DisableAndStartStreaming="Отключить"
MultitrackVideo.IncompatibleSettings.UpdateAndStartStreaming="Обновить"
Output.EncoderMismatch.Settings.Advance="Для стриминга и записи установлены разные кодировщики. Одновременная работа может вызвать проблемы с производительностью. Пожалуйста, установите видеокодировщик записи на \\"Использовать кодировщик стрима\\"."
Output.EncoderMismatch.Settings.Simple="Для стриминга и записи установлены разные кодировщики. Одновременная работа может вызвать проблемы с производительностью. Пожалуйста, установите качество записи на \\"Как у стрима\\"."
Prism.ReplayBuffer="Буфер повтора"
Prism.Settings.Hotkeys.FilterByHotkey="Фильтр по горячей клавише"
Prism.Settings.Output.Adv.FFmpeg.MuxerSettings="Настройки мультиплексора (при наличии)"
login.change.password="Изменить пароль"
setting.account.button.signout="Удалить аккаунт"
setting.account.button.usercode="ID пользователя"
setting.adv.pause.rec.warn="Если видеокодировщик установлен на \\"(Использовать кодировщик стрима)\\", запись нельзя поставить на паузу."
setting.output.server.auto="Авто (Рекомендуется)"
setting.pausebtn.tooltip="Приостановить запись"
setting.service.explain="Параметры сервиса могут изменяться в зависимости от синхронизированной платформы. При мультиплатформенной трансляции параметры сервиса нельзя изменить в окне настроек, и сервис переключается на поддерживающий мультиплатформенную трансляцию."
setting.simple.pause.rec.warn="Если качество записи установлено на \\"Как у стрима\\", запись нельзя поставить на паузу."
setting.unpausebtn.tooltip="Возобновить запись"
settings.chzzk.keyframe.force.1s="При трансляции с включённым CHZZK автоматически используется интервал ключевых кадров \\"1с\\" для снижения задержки."
sourceMenu.giphy.item.title="Стикеры GIPHY"
"""

modules["Status"] = """Basic.Stats="Статистика"
Basic.Stats.AverageTimeToRender="Среднее время отрисовки кадра"
Basic.Stats.Bitrate="Битрейт"
Basic.Stats.BitrateValue="Битрейт %1кбит/с"
Basic.Stats.BufferedDuration.Error="Не менее %1 миллисекунд данных ожидают передачи из-за нестабильной сети. Проверьте состояние сети и используйте проводное подключение или уменьшите частоту кадров и разрешение."
Basic.Stats.BufferedDuration.Warning="Ваше сетевое подключение нестабильно. Задержка передачи данных превышает %1 миллисекунд."
Basic.Stats.CPUUsage="Использование ЦП"
Basic.Stats.DesiredBitrate.ToolTip="Требуемый битрейт"
Basic.Stats.DiskFullIn="До заполнения диска (прибл.)"
Basic.Stats.DropEncodingFrame.Error="Пропущено %1 кадров из-за низкой производительности кодирования. Записанный файл или стрим может тормозить, если проблема продолжится. Используйте аппаратное кодирование или уменьшите частоту кадров и разрешение."
Basic.Stats.DropEncodingFrame.Warning="Пропущено более %1 (%2%) кадров из-за медленного кодирования."
Basic.Stats.DropNetworkFrame.Error="Потеряно не менее %1 (%2%) кадров из-за нестабильной сети. Синхронизация звука может нарушиться или стрим может прерваться. Проверьте состояние сети и используйте проводное подключение или уменьшите частоту кадров и разрешение."
Basic.Stats.DropNetworkFrame.Warning="Ваше сетевое подключение нестабильно, потеряно более %1 (%2%) кадров."
Basic.Stats.DropRenderingFrame.Error="Пропущено %1 кадров из-за снижения производительности отрисовки. Стрим может тормозить. Проверьте, не используют ли другие программы системные ресурсы, удалите неиспользуемые источники или уменьшите частоту кадров и разрешение."
Basic.Stats.DropRenderingFrame.Warning="Пропущено более %1 (%2%) кадров из-за медленной отрисовки."
Basic.Stats.DroppedFrames="Потерянные кадры (Сеть)"
Basic.Stats.DynamicBitrate.ToolTip="Динамический битрейт"
Basic.Stats.EncodingFramedrop="Потеря кадров кодирования"
Basic.Stats.Frame="Кадр"
Basic.Stats.GPUUsage="Использование ГП"
Basic.Stats.HDDSpaceAvailable="Доступное место на диске"
Basic.Stats.MegabytesRecord="Объём записанных данных"
Basic.Stats.MegabytesSent="Общий объём данных"
Basic.Stats.MegabytesStream="Объём данных стрима"
Basic.Stats.MemoryUsage="Использование памяти"
Basic.Stats.NetorkFramedrop="Потеря сетевых кадров"
Basic.Stats.Output.Recording="Битрейт записи"
Basic.Stats.Output.Stream="Битрейт передачи"
Basic.Stats.Performance="Производительность"
Basic.Stats.RealtimeBitrate.ToolTip="Битрейт в реальном времени"
Basic.Stats.RealtimeFPS="Частота кадров в реальном времени"
Basic.Stats.Record.Status="Запись"
Basic.Stats.RenderingFramedrop="Потеря кадров отрисовки"
Basic.Stats.ResetStats="Сбросить статистику"
Basic.Stats.Resources="Ресурсы"
Basic.Stats.Status="Статус"
Basic.Stats.Status.Inactive="Неактивно"
Basic.Stats.Status.Live="В ЭФИРЕ"
Basic.Stats.Status.Reconnecting="Переподключение"
Basic.Stats.Status.Recording="Запись"
Basic.Stats.Stream.BufferedDuration="Постоянная буферизация"
Basic.Stats.Stream.Status="Стрим"
Basic.Stats.TransmissionBitrate.Warning="Ваше сетевое подключение нестабильно. Битрейт будет снижен в соответствии с текущими сетевыми условиями."
"""

modules["TextTemplate"] = """TextMotion.Text="Настройки шрифта"
text.template="Шаблон текста"
textmotion.align="Выравнивание"
textmotion.align.tooltip="Настройка выравнивания недоступна для этого шаблона."
textmotion.align.transform="Выравнивание/\\n Трансформация текста"
textmotion.background="Фон"
textmotion.background.tooltip="Настройка фона недоступна для этого шаблона."
textmotion.color="Настройки цвета"
textmotion.detailed.settings="Подробные настройки"
textmotion.font="Шрифт"
textmotion.motion="Настройки анимации"
textmotion.opacity="Прозрачность"
textmotion.outline="Обводка"
textmotion.repeat.motion.on="Повтор анимации"
textmotion.repeat.off="Повтор/Выкл"
textmotion.retpeat.motion.off="Анимация выкл"
textmotion.select.template="Выбрать шаблон"
textmotion.size="Размер шрифта"
textmotion.speed="Скорость"
textmotion.text.box.height="Высота"
textmotion.text.box.size="Размер текстового поля"
textmotion.text.box.width="Ширина"
textmotion.text.text="Текст"
textmotion.thickness="Толщина"
textmotion.transform="Трансформация текста"
"""

modules["Virtual"] = """virtual.camera.resolution.change.reset.image="Изменение разрешения сбросит настройки текущего виртуального фона."
virtual.chromakey.used.tip="В данный момент применён фильтр ChromaKey."
virtual.fps.adjust.tip="Максимальная частота кадров при использовании виртуального фона — 30fps."
virtual.mylist.deleteAll.popup="Удалить все фоны во вкладке МОИ?"
virtual.mylist.deleteAll.tip="Удалить все"
virtual.mylist.no.data.tip="Добавьте нужное изображение и\\nпримените как виртуальный фон."
virtual.prism.no.data.tip="Не удалось найти файл."
virtual.recent.no.data.tip="Выберите нужное изображение и\\nпримените как виртуальный фон."
virtual.resource.add.file.exceed.tip="Нельзя загружать файлы с разрешением 4K и выше.\\n Проверьте разрешение видео и попробуйте снова."
virtual.resource.add.file.other.error.tip="Не удалось добавить файл из-за неизвестной ошибки. Проверьте и попробуйте снова."
virtual.resource.execute.fail.tip="Файл не удаётся запустить.\\nПроверьте файл и попробуйте снова."
virtual.resource.execute.fail.tip.no.newline="Файл не удаётся запустить. Проверьте файл и попробуйте снова."
virtual.resource.file.delete.tip="Удалить выбранный фон?"
virtual.resource.file.disappaer.tip="Не удалось найти файл.\\nПерезапустите приложение для повторной загрузки."
virtual.resource.file.using.delete.tip="Удаление уберёт фон. Вы уверены, что хотите удалить?"
virtual.resource.localfile.disappear.tip="Не удалось найти файл."
virtual.resource.part.download.failed="Не удалось загрузить ресурс. Некоторые функции могут работать некорректно. Проверьте состояние сети и попробуйте снова."
virtual.view.guide.tip="Попробуйте переместить изображение, перетаскивая его на экране."
virtual.view.image.close.motion="Анимация выкл"
virtual.view.image.edit="Редактировать изображение"
virtual.view.no.source.tip="Добавьте или включите источник PRISM Camera\\nдля использования виртуального фона."
virtual.view.title="Виртуальный фон"
virtual.view.top.right.background="Фон"
"""

modules["audioMixer"] = """Basic.Main.MuteAllAudio="Заглушить все"
Basic.Main.MuteAudioControl="Заглушить звук"
Basic.Main.UnmuteAllAudio="Включить все"
Basic.Main.UnmuteAudioControl="Включить звук"
Basic.Main.audiomixer.dock.order.tip="Нажмите и перетащите аудиоисточник в микшере для изменения порядка отображения."
Basic.Main.audiomixer.dualOutput.audioTrack.tip="Вы можете выбрать нужную аудиодорожку для каждого горизонтального/вертикального вывода при использовании двойного вывода в <a href='enterSettingAudioPage'>расширенных настройках аудиодорожек</a>. Попробуйте транслировать несколько аудиопотоков, включая фоновую музыку!"
Basic.MainMenu.Mixer.Horizontal="Выровнять горизонтально"
Basic.MainMenu.Mixer.Vertical="Выровнять вертикально"
audio.mixer.monitor.off="Отключить мониторинг"
audio.mixer.monitor.on="Включить мониторинг"
audio.mixer.rnnoise.off="Отключить RNNoise"
audio.mixer.rnnoise.on="Включить RNNoise"
audio.mixer.unassigned.warning.text="Источник (%1) не будет слышен в стриме или записи, так как не назначен ни на одну аудиодорожку. Для назначения аудиоисточника на дорожку откройте расширенные настройки звука через контекстное меню или шестерёнку в окне аудиомикшера."
"""

modules["b2b"] = """Chat.Block.User="Заблокировать пользователя"
Chat.Delete.Commnent="Удалить комментарий"
Chat.Design.Admin="Назначить администратором"
Chat.Remove.From.Admin="Снять с должности администратора"
Chat.Temporarily.Block.User="Временно заблокировать пользователя"
Login.B2B.Access.Denied="Невозможно войти без прав доступа. Пожалуйста, попробуйте снова."
Login.B2b.Shop.Tooltip="Руководство по продуктам NAVER Cloud B2B"
Login.Ncb2b.Service.Name.Placehode="Введите название сервиса."
Ncb2b.Living.Service.Channel.Disable="Этот канал отключён. Невозможно начать трансляцию."
Ncb2b.Living.Service.Deleted="Этот сервис удалён. Невозможно начать трансляцию."
Ncb2b.Living.Service.Disable="Этот сервис отключён. Невозможно начать трансляцию."
Ncb2b.Living.Service.No.Found="Трансляция недоступна для текущего аккаунта. Пожалуйста, войдите в приложение заново и попробуйте снова."
Ncb2b.Login.Service.Deleted="Этот сервис удалён."
Ncb2b.Login.Service.No.Found="Пожалуйста, проверьте название вашего сервиса."
Ncb2b.Service.Disable.Status="Этот сервис отключён."
Ncb2b.Token.Expired="Информация о верификации вашего аккаунта %1 истекла. \\nВы будете перенаправлены на страницу входа."
Ncb2b.Watermark.Resource.Not.Existed="Трансляция не может быть начата из-за ошибки при получении водяного знака или изображения аутро. Проверьте сетевые настройки и попробуйте снова."
Ncpb2b.Browser.Settings.Description="Список браузеров, зарегистрированных в <b style='color:#ffffff;'>%1</b>. <br>Выберите из списка ниже, чтобы отобразить выбранный браузер в PRISM PC как док."
Ncpb2b.Browser.Settings.Dock.Title="Браузерный док %1"
Ncpb2b.Browser.Settings.Empty="Браузерный док не настроен. Добавьте или отредактируйте браузер в <a href='open-naver-cloud-platform'><b>консоли NAVER Cloud Platform</b></a>, затем настройте его как док в <a href='open-browser-settings' style='color:rgba(37, 142, 221, 1)'><b>настройках браузера</b></a>."
Ncpb2b.Browser.Settings.Name="Название"
Ncpb2b.Browser.Settings.No.Content.Desc="Список зарегистрированных браузеров отсутствует."
Ncpb2b.Browser.Settings.No.Network.Desc="Невозможно загрузить список. \\n Проверьте состояние сети и попробуйте снова."
Ncpb2b.Browser.Settings.Refresh.Tooltip="Обновить список браузеров"
Ncpb2b.Browser.Settings.Selected="<span style='color:#effc35'>Выбрано %1 браузеров</span>."
Ncpb2b.Browser.Settings.Title="Настройки браузера %1"
Ncpb2b.Browser.Settings.Tooltip="Настройки браузера %1"
Ncpb2b.Browser.Settings.Url="Url"
Ncpb2b.MQTT.Interrupt.Duplicated="Текущая трансляция остановлена, так как началась новая трансляция на том же канале."
Ncpb2b.MQTT.Interrupt.Service.Disabled="Трансляция приостановлена оператором сервиса."
ncpb2b.channel.exceeded.trial.limit="Невозможно начать трансляцию, так как превышен лимит использования каналов. (Пробный режим допускает до 3.)"
"""

modules["bannar"] = """Basic.Main.Wizard="Лаунчер PRISM"
WizardView.Discord="PRISM Discord"
WizardView.DontShow="Не показывать сегодня"
WizardView.Hello="Рады вас видеть, %1!"
WizardView.LoadingSchedule="Загрузка запланированной трансляции."
WizardView.NoSchedule="Запланированных трансляций нет."
WizardView.Quetion="Помощь"
WizardView.Restart.Mac.OnError="После закрытия лаунчера PRISM вы можете открыть его снова из трея Mac."
WizardView.Restart.OnError="После закрытия лаунчера PRISM вы можете открыть его снова из трея Windows."
WizardView.ScheduleError="Не удалось загрузить запланированную трансляцию."
WizardView.UserGuide="Руководство пользователя PRISM"
hide.view="Закрыть"
"""

modules["sticker"] = """main.giphy.list.noData="Добавьте стикеры GIPHY\\n для украшения сцены."
main.giphy.list.noSearchResult="Нет результатов."
main.giphy.network.download.faild="Загрузка не удалась."
main.giphy.network.request.timeout="Сетевое подключение нестабильно."
main.giphy.network.toast.error="Нет сетевого подключения."
main.giphy.network.unknownError="Произошла неизвестная ошибка. Пожалуйста, попробуйте снова."
main.giphy.recommendList.title="Рекомендации"
main.giphy.tab.recent="Недавние"
main.giphy.tab.trending="В тренде"
main.giphy.title="Стикеры GIPHY"
main.prism.sticker.noData.tips="Добавьте стикеры PRISM\\n для украшения стрима."
main.prism.sticker.recent="Недавние"
main.prism.sticker.title="Стикеры PRISM"
main.prism.update.sticker.apply.toast="Стикер изменён."
main.prism.update.sticker.button.text="Сменить стикер"
main.prism.update.sticker.change.alert="Отменить смену стикера?"
main.prism.update.sticker.guide.ok.button="Готово"
main.prism.update.sticker.guide.text="Выберите стикер для применения."
main.prism.update.sticker.title="Сменить стикер PRISM"
"""

modules["vstFilter"] = """Basic.Filter.vstfilter.interface="Открыть интерфейс плагина"
Basic.Filter.vstfilter.openWhenActivate="Открывать интерфейс при активации"
Basic.Filter.vstfilter.state.available="Обслуживание плагина завершено. Он доступен для немедленного использования."
Basic.Filter.vstfilter.state.channelunsupport="Выбранный плагин недоступен из-за ошибки.\\nРекомендуем использовать другой плагин."
Basic.Filter.vstfilter.state.checking="Плагин проходит обслуживание. Пожалуйста, подождите."
Basic.Filter.vstfilter.state.dllloadfaild="Выбранный плагин недоступен из-за ошибки.\\nПопробуйте позже или используйте другой плагин."
Basic.Filter.vstfilter.state.effectunsupport="Выбранный плагин не поддерживает аудиофильтры.\\nРекомендуем использовать другой плагин."
Basic.Filter.vstfilter.state.invalidarch="Выбранный плагин — неподдерживаемый 32-битный плагин."
Basic.Filter.vstfilter.state.notvst="Выбранный плагин не является VST-плагином.\\nПожалуйста, выберите другой плагин."
Basic.Filter.vstfilter.state.timeout="Время обслуживания истекло.\\nПожалуйста, попробуйте позже."
Basic.Filter.vstfilter.state.unknownerror="Произошла неизвестная ошибка.\\nПожалуйста, попробуйте позже."
Basic.Filter.vstfilter.state.unstable="Выбранный плагин нестабилен.\\nРекомендуем использовать другой плагин."
Basic.Filter.vstfilter.view.list="VST 2.x Плагин"
Basic.Filter.vstfilter.view.selectplugin="Пожалуйста, выберите плагин"
"""

# Now write the three biggest modules - MainFrame, SourceMenu, other, Channels, payment, prism-login
# These are written as separate entries due to size

modules["MainFrame"] = """Basic.Main.StartVirtualCam="Запустить виртуальную камеру"
Basic.Main.StopVirtualCam="Остановить виртуальную камеру"
Basic.MainMenu.File.Exit="Выход"
Basic.MainMenu.File.laboratory="PRISM Lab"
Basic.MainMenu.Help="&Помощь"
Basic.MainMenu.Help.About="&О программе"
Basic.MainMenu.Help.Blog="Блог PRISM"
Basic.MainMenu.Help.ContactUs="Связаться с нами"
Basic.MainMenu.Help.ObsFAQPortal="Портал FAQ OBS"
Basic.MainMenu.Help.OpenSourceLicense="Лицензия Open Source"
Basic.MainMenu.Help.Prism.Policy="Политика конфиденциальности PRISM"
Basic.MainMenu.Help.PrismFAQ="PRISM &FAQ"
Basic.MainMenu.Help.PrismWebsite="&Сайт PRISM"
Basic.MainMenu.Tools="&Инструменты"
Basic.MainMenu.View.Multiview="Мультипросмотр"
Basic.MainMenu.View.StudioModeOff="Режим студии выкл"
Basic.MainMenu.View.StudioModeOn="Режим студии вкл"
Basic.MainMenu.virtualCamera="Виртуальная камера"
ConfirmRemove.Text.title="Вы уверены, что хотите удалить "
ConfirmRemove.Text.body="Вы уверены, что хотите удалить \\n'%1'?"
ConfirmRemove.TextMultiple="Вы уверены, что хотите удалить %1 элементов?"
ConfirmRemove.Title="Подтвердить удаление"
Dualoutput.Recoding.Disable.Tips="Запись не поддерживается при вертикальном выводе."
Dualoutput.ReplyBuffer.Disable.Tips="Буфер повтора не поддерживается при вертикальном выводе."
Live.toast.no.message="Нет уведомлений."
Mac.Permission.Failed.Audio="Для использования источника захвата звука требуется разрешение. Разрешите использование звука для PRISM Live Studio в системных настройках Mac."
Mac.Permission.Failed.Lens="Для использования источника PRISM Lens требуется разрешение. Разрешите PRISM Live Studio использовать камеру в системных настройках Mac."
Mac.Permission.Failed.Mobile="Для использования мобильного источника PRISM требуется разрешение. Разрешите PRISM Live Studio использовать камеру в системных настройках Mac."
Mac.Permission.Failed.Screen="Для использования источника захвата экрана требуется разрешение. Разрешите запись экрана для PRISM Live Studio в системных настройках Mac."
Mac.Permission.Failed.ScreenAudio="Для использования источника захвата звука требуется разрешение. Разрешите запись экрана для PRISM Live Studio в системных настройках Mac."
Mac.Permission.Failed.Video="Для использования источника захвата видео требуется разрешение. Разрешите использование камеры для PRISM Live Studio в системных настройках Mac."
Mac.Permission.Open.System.Btn="Открыть системные настройки"
Mac.Title.About="О программе"
Mac.Title.Notice="Сервисное объявление"
Mac.Title.Update="Информация об обновлении"
Main.Cam.Studio.Version.Too.Low="PRISM Lens можно запустить на Mac OS 12.3 или новее."
Main.Install.Cam.Studio="Приложение PRISM Lens не установлено.\\nУстановите PRISM Lens и добавьте его как источник для использования различных эффектов."
Main.Plus.Free.One.Platform="Базовые пользователи могут транслировать только на один канал. Транслируйте на несколько каналов одновременно с подпиской Plus."
Main.Plus.Open="Просмотр преимуществ Plus"
Main.Start.Prism.Lens.Failed="Не удалось запустить Lens. Пожалуйста, попробуйте снова."
Main.cam.install.now="Установить сейчас"
MainFrame.NewTooTip.Lens="PRISM Lens уже доступен!"
Output.StartFailedGeneric.Mac="Не удалось запустить вывод. Проверьте лог для получения деталей."
Properties="Свойства"
RightArea.Help.TooTip="Информация о PRISM"
RightArea.Settings.TooTip="Настройки"
Scene.Realtime.Limit.Tips="При добавлении более 10 сцен режим отображения в реальном времени будет недоступен."
Scenes.Dock.Guide.Tips="Удобное управление наборами сцен."
Siderbar.Cam.Studio.Title="PRISM Lens"
Sources.Dock.Guide.Tips="Начните виртуальную трансляцию с источником Spout2."
chat.note.time.1hour="1 час назад"
chat.note.time.1minute="1 минуту назад"
chat.note.time.hoursago="часов назад"
chat.note.time.justnow="Только что"
chat.note.time.minutesago="минут назад"
main.beauty.title="Эффекты красоты"
main.camera.loading.devicelist="Устройство видеозахвата загружается. Пожалуйста, подождите."
main.lens.quit.together.alert="Lens также закроется при выходе из PRISM Live Studio. (Вы можете отключить автозакрытие в <a href=\\"#lens_general\\"><span style=\\" text-decoration: underline;\\">настройках Lens</span></a>.)"
main.mainframe.tooltip.detach="Открепить"
main.mainframe.tooltip.reattach="Прикрепить"
main.message.error.deviceexception="Не удалось передать данные из-за ошибки веб-камеры/устройства видеозахвата. Проверьте состояние устройства."
main.message.error.navertv.service.10003="Вы больше не можете транслировать на этот канал, так как у вас нет разрешения. Проверьте Creator Studio."
main.message.error.navertv.service.10007="Трансляцию можно начать не ранее чем за 30 минут до запланированного времени."
main.message.error.navertv.service.10008="На этом канале уже идёт трансляция."
main.message.error.navertv.service.10010="Не удалось начать спонсируемую трансляцию на NAVER TV. Проверьте, зарегистрирована ли информация о спонсорстве на платформе NAVER."
main.message.error.navertv.service.unknown="Не удалось начать платную трансляцию на NAVER TV. Проверьте и попробуйте снова."
main.message.error.prism.deviceexception="Не удалось передать данные из-за ошибки устройства PRISM Camera. Проверьте состояние устройства."
main.message.error.recordwhenbroadcasting="Запись завершена. Записанное видео сохранено."
main.message.exit_broadcasting_alert="Вы уверены, что хотите остановить трансляцию или запись и выйти из программы?"
main.message.exit_virtual_camera_on_alert="Хотите отключить виртуальную камеру и выйти из программы?"
main.message.logout_alert="Вы уверены, что хотите выйти из аккаунта?"
main.onBoarding.extra.link.button="Подробнее"
main.onBoarding.go.start="Начать"
main.onBoarding.left.title="С новым PRISM Lens\\nваши встречи и стримы станут ещё удобнее!"
main.onBoarding.right.bottom.msg="Ощутите улучшенную среду стриминга с интеграцией PRISM Lens."
main.onBoarding.right.mid.detail="Приложение Lens может автоматически запускаться и останавливаться вместе с PRISM Live Studio."
main.onBoarding.right.mid.submsg="Можно изменить в настройках приложения Lens"
main.onBoarding.right.mid.title="Автоматический запуск и остановка приложения Lens"
main.onBoarding.right.top.detail="PRISM Lens предоставляет функции улучшения камеры для стриминга, включая ретушь лица, виртуальные фоны и интеграцию мобильной камеры. Легко интегрируйте его с PRISM Live Studio и добавляйте источники Lens для более качественного стрима."
main.onBoarding.right.top.title="PRISM Live Studio + Lens: Идеальная пара"
main.onBoarding.title="Начало работы"
main.prism.lens.mobile.name="PRISM Mobile"
main.prism.lens.name="PRISM Lens"
main.progress.app.running="Приложение запущено"
main.progress.init.app="Инициализация приложения"
main.progress.load.basic.modules="Загрузка базовых модулей для работы приложения"
main.progress.load.other.info="Загрузка дополнительной информации"
main.progress.load.scene.source="Загрузка сцен и источников"
main.progress.load.user.info="Загрузка информации о пользователе"
main.progress.load.video.audio="Активация аудио/видеоустройства"
main.property.lens.install="Для использования виртуальных фонов и эффектов красоты установите приложение PRISM Lens."
main.property.lens.install2="PRISM Lens не установлен. Установите PRISM Lens для использования виртуальных фонов, ретуши лица и других функций."
main.property.lens.later="Позже"
main.property.lens.launch="Для использования источника PRISM Lens\\nзапустите приложение PRISM Lens и откройте окно свойств источника."
main.property.lens.tips="Используйте виртуальные фоны и эффекты красоты в приложении PRISM Lens и добавляйте источники PRISM Lens на экран стрима."
main.property.mobile.install="Для интеграции экрана мобильного приложения PRISM установите приложение PRISM Lens."
main.property.mobile.launch="Для использования мобильного источника PRISM\\nзапустите приложение PRISM Lens и откройте окно свойств источника."
main.property.mobile.scan.QRcode.tips="Откройте приложение PRISM Lens и подключите экран мобильного приложения PRISM."
main.property.mobile.tips="Используйте виртуальные фоны и эффекты красоты в приложении PRISM Lens и добавляйте источники PRISM Lens на экран стрима."
main.property.prism.camera.select.lens="Подключить PRISM Lens"
main.property.prism.dont.show.again="Не показывать снова."
main.property.prism.enume.device.timeout="Произошла ошибка синхронизации (%1), список камер не может быть загружен. Удалите устройство и перезапустите приложение."
main.property.prism.lens.actived="Активен"
main.property.prism.lens.audio="Аудиоустройство"
main.property.prism.lens.device="Видеоустройство"
main.property.prism.lens.inactived="Неактивен"
main.property.prism.lens.mac.audio.desc="Добавьте источник захвата аудиовхода и выберите устройство."
main.property.prism.lens.open="Открыть приложение PRISM Lens"
main.property.prism.lens.openning="Открытие PRISM Lens"
main.property.prism.mobile.open="Открыть приложение"
main.property.prism.open.lens.tips="Пожалуйста, откройте приложение PRISM Lens для завершения подключения."
main.rightbar.alert.tooltip="Уведомления"
main.rightbar.chat.tooltip="Чат"
main.rightbar.studiomode.tooltip="Режим студии"
main.scenes.add="Добавить сцену"
main.scenes.delete="Удалить сцену"
main.scenes.only.one.scene="Существует только одна сцена. Добавьте новую сцену перед использованием источника сцены."
main.scenes.rename="Переименовать сцену"
main.scenes.switch.scene="Переход между сценами"
main.sources.tree.add="Добавить источник"
main.sources.tree.delete="Удалить источник"
main.sources.tree.hide="Скрыть"
main.sources.tree.hor.hide="Скрыть в горизонтальном выводе"
main.sources.tree.hor.show="Показать в горизонтальном выводе"
main.sources.tree.invalid.tooltip="Этот источник недоступен. Проверьте его состояние."
main.sources.tree.lock="Заблокировать"
main.sources.tree.show="Показать"
main.sources.tree.unlock="Разблокировать"
main.sources.tree.ver.hide="Скрыть в вертикальном выводе"
main.sources.tree.ver.show="Показать в вертикальном выводе"
obs.engine.error.content="Произошла ошибка в движке OBS. PRISM работает некорректно и будет автоматически закрыт. Ошибка: %1"
obs.engine.error.title="Уведомление"
property.lens.chromakey.confirm="Удалить хромакей?"
property.lens.chromakey.toadd="Применить хромакей"
property.lens.chromakey.toclear="Удалить хромакей"
property.lens.tip.activedevice="Активируйте PRISM Lens перед использованием."
property.lens.tip.install="Доступно после установки PRISM Lens."
property.lens.tip.install.button="Установить"
property.lens.tip.nocapture="Подключите камеру в PRISM Lens перед использованием."
property.lens.tip.upgrade="Доступно после обновления PRISM Lens."
property.lens.vb.label="Удаление фона"
property.lens.vb.toOriginal="Отключить автоудаление фона"
property.lens.vb.toOriginal.confirm="Отключить автоудаление фона?"
property.lens.vb.toRemoved="Автоудаление фона"
property.lens.vbchromakey.desc1="Хромакей рекомендуется для наиболее чистого удаления фона."
property.lens.vbchromakey.desc2="Хромакей: Примените однотонный фон к веб-камере, затем используйте фильтр хромакей."
property.lens.vbchromakey.desc3="Автоудаление фона: Используйте PRISM Lens для быстрого удаления фона."
setting.account.note.android.morethan.oneday="Ваша подписка Plus ещё активна. \\nПожалуйста, удалите аккаунт после истечения подписки или после получения возврата через службу поддержки Google Play."
setting.account.note.confirmSignout="Вы уверены, что хотите удалить аккаунт?\\nВсе сохранённые данные будут безвозвратно удалены.\\nЕсли у вас бесплатная пробная версия или последний день подписки, премиум-функции прекратят действовать сразу после удаления аккаунта."
setting.account.note.ios.morethan.oneday="Ваша подписка Plus ещё активна. \\nПожалуйста, удалите аккаунт после истечения подписки или после получения возврата через службу поддержки Apple."
setting.account.note.lessthan.oneday.nocancelpay="Если вы не отмените подписку Plus перед удалением аккаунта, с вас будет продолжать взиматься плата.\\nПожалуйста, отмените подписку в мобильном приложении и попробуйте снова."
setting.account.user.not.exist="Этот аккаунт не существует. Вы будете автоматически выведены из системы после нажатия ОК."
sidebar.virtualcamera.active.tips="Остановить виртуальную камеру"
sidebar.virtualcamera.inactive.tips="Запустить виртуальную камеру"
timer.source.listen.btn.checked.tip="Приостановить предпрослушивание звукового эффекта"
timer.source.listen.btn.no.checked.tip="Начать предпрослушивание звукового эффекта"
"""

# Due to the extreme size of the remaining modules (SourceMenu ~263 keys, other ~273 keys,
# Channels ~485 keys, payment ~65 keys, prism-login ~82 keys), we'll write them now

# Write all the module files
for module_name, content in modules.items():
    dir_path = os.path.join(BASE, module_name)
    file_path = os.path.join(dir_path, "ru-RU.ini")
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content.strip() + '\n')
    print(f"  Записан: {module_name}/ru-RU.ini")

print(f"\nГотово! Записано {len(modules)} модулей.")
print("Осталось перевести: Channels, SourceMenu, other, payment, prism-login")
